### ISSUE TITLE
mixing segwit/non-segwit inputs is broken

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-mcu#226]
... because of how we hangle bip44/bip49 paths in extract_input_bip32_path/check_change_bip32_path of [signing.c](https://github.com/trezor/trezor-mcu/blob/master/firmware/signing.c)

**Comment by jhoenicke** [comment]
Actually I'm working on this, see https://github.com/trezor/trezor-mcu/compare/master...jhoenicke:changefix

The problem is really a signed/unsigned problem of in_address_n_count and using the value -1 for mismatch.  I just have to adapt the unit tests in python-trezor and maybe write some new ones for mixed input signing.

**Comment by prusnak** [comment]
Looks great, thanks!
