### ISSUE TITLE
Q: Why are prevTxs needed?

### ISSUE THREAD

**Issue by kento1218** [trezor/trezor-mcu#366]
From my understanding, when considering signing procedure, parameters really needed are: `inputs` and `outputs` to sign and `OutPoint` of each `inputs`. But TREZOR firmware requires fully `prevTxs` (including inputs of each `prevTx`) and checks consistency between `inputs` and `PrevTxs` ([here](https://github.com/trezor/trezor-mcu/blob/master/firmware/signing.c#L595)).

1. Why are those needed?
2. Is there any way to skip `prevTxs` verification?

I found this issue, mentioned about `prevTxs`, but I think the verification process was not mostly changed since that. (except segwit support) https://github.com/trezor/trezor-mcu/issues/63

Background:
We're creating an offline signing application using TREZOR. Due to restriction of payload size of our data-transfer mechanism for offline system, we'd like to reduce size of parameters.

**Comment by prusnak** [comment]
1. Transactions before segwit don't contain amounts in inputs, so one has to compute this from prevtx (because prevtx has this value in output). Segwit transactions do not have this problem (they include amount in input), so prevtx is not needed.
2. No for old transactions, segwit tx don't require it

> we'd like to reduce size of parameters

Easy, support only segwit tx.
